#' @title Matched Multiply Imputed Datasets
#'
#' @docType class
#'
#' @aliases mimids
#'
#' @rdname mimids
#'
#' @name mimids
#'
#' @description \code{mimids} object contains data of matched multiply imputed datasets. \code{mimids} objects are generated by calls to \code{matchthem()}.
#'
#' @details \code{mimids} objects have methods for \code{print()}, \code{summary()}, \code{plot()}, and \code{\link[=cbind.mimids]{cbind()}}.
#'
#' @note The \pkg{MatchThem} package does not use the S4 class definitions and instead relies on the S3 list equivalents.
#'
#' @seealso \code{\link[=matchthem]{matchthem}}
#'
#' @author Farhad Pishgar
#'
#' @references Stef van Buuren and Karin Groothuis-Oudshoorn (2011). \code{mice}: Multivariate Imputation by Chained Equations in \code{R}. \emph{Journal of Statistical Software}, 45(3): 1-67. \url{https://www.jstatsoft.org/v45/i03/}
#'
#' @keywords classes

NULL

#object: Original 'mids' object augmented with estimated weights
#models: 'weightit' objects
#datasets: Imputed datasets with estimated weights (lapply(0:m, .(i) complete(W$object, i)))
#others: List with source, which is the original 'mids' object