#' @title Multiply Imputed Repeated Analyses
#'
#' @docType class
#'
#' @aliases mimira
#'
#' @rdname mimira
#'
#' @name mimira
#'
#' @description `mimira` object contains data of multiply imputed repeated analyses. `mimira` objects are generated by calls to `with()`.
#'
#' @details `mimira` objects has methods for the `print()` and `summary()` functions (please see \pkg{mice} package reference manual for details).
#'
#' @note The \pkg{MatchThem} package does not use the S4 class definitions and instead relies on the S3 list equivalents.
#'
#' @seealso [with()]
#'
#' @author Farhad Pishgar
#'
#' @references Stef van Buuren and Karin Groothuis-Oudshoorn (2011). `mice`: Multivariate Imputation by Chained Equations in `R`. *Journal of Statistical Software*, 45(3): 1-67. \doi{10.18637/jss.v045.i03}
#'
#' @keywords classes

NULL
