#' @title Weighted Multiply Imputed Datasets
#'
#' @docType class
#'
#' @aliases wimids
#'
#' @rdname wimids
#'
#' @name wimids
#'
#' @description `wimids` object contains data of weighted multiply imputed datasets. The `wimids` object is generated by calls to the `weightthem()`.
#'
#' @details `wimids` objects have methods for `print()`, `summary()`, and [`cbind()`][cbind.mimids].
#'
#' @note The \pkg{MatchThem} package does not use the S4 class definitions and instead relies on the S3 list equivalents.
#'
#' @seealso [weightthem()], [as.wimids()]
#'
#' @author Farhad Pishgar
#'
#' @references Stef van Buuren and Karin Groothuis-Oudshoorn (2011). `mice`: Multivariate Imputation by Chained Equations in `R`. *Journal of Statistical Software*, 45(3): 1-67. \doi{10.18637/jss.v045.i03}
#'
#' @keywords classes

NULL
